name: Challenge
version: '${project.version}'
main: me.gamerpvg.challenge.Main
api-version: 1.19
authors: [ GamerPvG ]
description: Ein Challengeplugin für einen Youtuber
website: https://www.emrage.org/
